language: python

python:
  - "3.5"
  
sudo: required

services:
  - docker

before_install:
  - docker pull dmm7aj/pccs

install:
  - pip install -q coveralls
  - pip install -q Django==1.10
  - pip install -q django-autocomplete-light==3.2.1
  - pip install -q django-bootstrap3==7.1.0
  - pip install -q django-widget-tweaks
  - pip install -q python-dateutil
  #- pip install -q django-bootstrap3-datetimepicker==2.2.3

script:
  - coverage run app/manage.py test
  - phantomjs test/js/run-qunit.js file://`pwd`/test/js/qunit.html\?coverage

after_success:
  coveralls
  
