language: python

python:
  - "3.5"

install:
  - pip install -q Django==1.10
  - pip install -q django-autocomplete-light==3.2.1
  - pip install -q django-bootstrap3==7.1.0
  - pip install -q django-widget-tweaks
  # - pip install -q django-bootstrap3-datetimepicker==2.2.3

script: python app/manage.py test app

sudo: false
