# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_target_contest'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Invite'),
        ),
        migrations.AddField(
            model_name='target',
            name='join_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.JoinRequest'),
        ),
        migrations.AddField(
            model_name='target',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
