# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_remove_alert_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alerts.Subject'),
        ),
    ]
