# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alert_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='alert',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='alerts.Alert'),
            preserve_default=False,
        ),
    ]
