# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_auto_20170102_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='subject',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='alert',
            name='body',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='subject',
            name='alert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='alerts.Alert'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
