# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_auto_20170102_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Target',
        ),
    ]
