# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_auto_20170110_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='organization',
        ),
    ]
