# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170123_1044'),
        ('teams', '0002_auto_20170127_1537'),
        ('teams', '0002_auto_20170122_2105'),
    ]

    operations = [
    ]
