# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20170125_1526'),
        ('teams', '0003_merge_20170129_1910'),
    ]

    operations = [
    ]
