# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.CharField(default='', max_length=128),
        ),
    ]
