# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-29 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.CharField(max_length=32)),
                ('languages', models.CharField(max_length=64)),
                ('contest_length', models.CharField(max_length=8)),
                ('time_penalty', models.CharField(max_length=4)),
                ('autojudge_enabled', models.BooleanField(max_length=1)),
                ('autojudge_review', models.CharField(max_length=128)),
                ('problem_description', models.CharField(max_length=128)),
                ('solutions', models.CharField(max_length=128)),
                ('contest_admins', models.TextField()),
                ('contest_participants', models.TextField()),
            ],
        ),
    ]
