# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.FileField(max_length=128, upload_to=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.FileField(max_length=128, upload_to=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.FileField(max_length=128, upload_to=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
