# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='original_filename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
