# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_solution', to='contests.Problem'),
        ),
        migrations.AddField(
            model_name='probleminput',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_input', to='contests.Problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
        ),
        migrations.AddField(
            model_name='participant',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AddField(
            model_name='notification',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Submission'),
        ),
    ]
