# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20161202_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
