# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20161106_1343'),
        ('contests', '0002_auto_20161105_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.ContestTemplate')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
    ]
