# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20161031_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_admins',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_participants',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
