# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('contests', '0002_auto_20170328_0137'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttemplate',
            name='contest_admins',
            field=models.ManyToManyField(blank=True, related_name='contesttemplate_admins', to='users.User'),
        ),
        migrations.AddField(
            model_name='contesttemplate',
            name='contest_participants',
            field=models.ManyToManyField(blank=True, related_name='contesttemplate_participants', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='contesttemplate',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contesttemplate_creator', to='users.User'),
        ),
        migrations.AddField(
            model_name='contestinvite',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
        ),
        migrations.AddField(
            model_name='contestinvite',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_admins',
            field=models.ManyToManyField(blank=True, related_name='contest_admins', to='users.User'),
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_participants',
            field=models.ManyToManyField(blank=True, related_name='contest_participants', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='contest',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_creator', to='users.User'),
        ),
    ]
