# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20170328_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.TextField(blank=True),
        ),
    ]
