# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20161127_0442'),
        ('contests', '0003_auto_20161126_2328'),
    ]

    operations = [
    ]
