# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20161202_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_length',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contest',
            name='time_penalty',
            field=models.CharField(max_length=30),
        ),
    ]
