# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20161102_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='length',
            new_name='contest_length',
        ),
    ]
