# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_merge_20161128_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='run_id',
            new_name='runID',
        ),
    ]
