# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_submission_run_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='autojudge',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='question',
        ),
        migrations.AddField(
            model_name='contest',
            name='autojudge_enabled',
            field=models.BooleanField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='autojudge_review',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='problem_description',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='time_penalty',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_admins',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_length',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_participants',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='languages',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.Contest'),
        ),
        migrations.DeleteModel(
            name='ContestTemplate',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
