# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contesttemplate'),
        ('contests', '0004_merge_20161128_1428'),
    ]

    operations = [
    ]
