# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20161113_1805'),
        ('contests', '0004_submission_run_id'),
    ]

    operations = [
    ]
