# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_merge_20161128_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='run_id',
        ),
    ]
