# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_submission_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttemplate',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
