# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20161114_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='problem_description',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads/'),
        ),
    ]
