# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20161129_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='runID',
            new_name='run_id',
        ),
    ]
