# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20161205_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='time_penalty',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
