# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20170409_2224'),
        ('contests', '0005_auto_20170401_1809'),
    ]

    operations = [
    ]
