# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_participant'),
        ('contests', '0005_auto_20161113_2344'),
    ]

    operations = [
    ]
