# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_submission_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='state',
            field=models.CharField(default='NEW', max_length=20),
        ),
    ]
