# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20161205_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
