# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20161114_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
