# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20161129_0247'),
        ('contests', '0005_merge_20161129_0502'),
    ]

    operations = [
    ]
