# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20161210_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='program_input',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
