# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_merge_20161130_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='contest_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
