# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_merge_20170410_1013'),
        ('contests', '0007_auto_20170412_1419'),
    ]

    operations = [
    ]
