# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20161114_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='autojudge_review',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
