# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_problem_program_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solution',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
