# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20161114_0348'),
        ('contests', '0008_merge_20161114_1721'),
    ]

    operations = [
    ]
