# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_auto_20170422_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probleminput',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_inputs', to='contests.Problem'),
        ),
    ]
