# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_merge_20161114_0418'),
    ]

    operations = [

    ]
