# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_merge_20161114_1737'),
        ('contests', '0010_auto_20161114_2220'),
    ]

    operations = [
    ]
