# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-25 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('contests', '0010_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_admins',
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_admins',
            field=models.ManyToManyField(related_name='contest_admins', to='users.User'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_creator', to='users.User'),
        ),
        migrations.RemoveField(
            model_name='contesttemplate',
            name='contest_admins',
        ),
        migrations.AddField(
            model_name='contesttemplate',
            name='contest_admins',
            field=models.ManyToManyField(related_name='contesttemplate_admins', to='users.User'),
        ),
        migrations.AlterField(
            model_name='contesttemplate',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contesttemplate_creator', to='users.User'),
        ),
    ]
