# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_auto_20170423_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probleminput',
            name='problem',
        ),
        migrations.AddField(
            model_name='problem',
            name='program_input',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='ProblemInput',
        ),
    ]
