# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_auto_20170423_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_input', models.FileField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='program_input',
        ),
        migrations.AddField(
            model_name='probleminput',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_input', to='contests.Problem'),
        ),
    ]
