# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_merge_20161115_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
