# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_auto_20170225_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='time_penalty',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contesttemplate',
            name='contest_length',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contesttemplate',
            name='time_penalty',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
