# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20170225_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='time_penalty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contesttemplate',
            name='time_penalty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
