# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20170425_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution',
        ),
        migrations.AddField(
            model_name='problemsolution',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_solution', to='contests.Problem'),
        ),
    ]
