# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20161115_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
