# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0012_auto_20161114_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
