# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_merge_20161114_0456'),
        ('contests', '0006_merge_20161114_0518'),
        ('contests', '0013_auto_20161114_0431'),
    ]

    operations = [
    ]
