# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_merge_20170201_1008'),
        ('contests', '0013_auto_20170225_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_participants',
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_participants',
            field=models.ManyToManyField(blank=True, related_name='contest_participants', to='teams.Team'),
        ),
        migrations.RemoveField(
            model_name='contesttemplate',
            name='contest_participants',
        ),
        migrations.AddField(
            model_name='contesttemplate',
            name='contest_participants',
            field=models.ManyToManyField(blank=True, related_name='contesttemplate_participants', to='teams.Team'),
        ),
    ]
