# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_merge_20161114_0624'),
        ('contests', '0014_merge_20161114_0557'),
    ]

    operations = [
    ]
