# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_auto_20170225_1541'),
        ('contests', '0014_auto_20170227_2113'),
    ]

    operations = [
    ]
