# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0015_merge_20170228_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='number',
        ),
    ]
