# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0016_remove_problem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='timeout',
            field=models.IntegerField(default=5),
        ),
    ]
