# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0017_problem_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='timeout',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
