# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0018_auto_20170319_2232'),
        ('contests', '0017_contestinvite'),
    ]

    operations = [
    ]
