# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('teams', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(to='users.User')),
                ('teams', models.ManyToManyField(to='teams.Team')),
            ],
        ),
    ]
